name: Test
body:
  - type: markdown
    attributes:
      value: Hello world!
  - type: input
    attributes:
      label: Username
description: Test.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: "victormrecabarren/1"
